const production = !process.env.ROLLUP_WATCH;
module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: {
    content: ["./src/**/*.svelte"],
    options: {
      safelist: [/data-theme$/],
    },
    enabled: production,
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        cursive: ["Satisfy"],
        sans: ["lato"],
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        desolate: {
          primary: "#570df8",
          "primary-focus": "#4506cb",
          "primary-content": "#ffffff",
          secondary: "#f07400",
          "secondary-focus": "#984a01",
          "secondary-content": "#000",
          accent: "#37cdbe",
          "accent-focus": "#2aa79b",
          "accent-content": "#000",
          neutral: "#3d4451",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          info: "#2094f3",
          success: "#51cf66",
          warning: "#ff922b",
          error: "#fa5252",
        },
        black: {
          primary: "#22b8cf",
          "primary-focus": "#1098ad",
          "primary-content": "#000",
          secondary: "#f07400",
          "secondary-focus": "#984a01",
          "secondary-content": "#000",
          accent: "#37cdbe",
          "accent-focus": "#2aa79b",
          "accent-content": "#000",
          neutral: "#2a2e37",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#000",
          "base-200": "#090a0b",
          "base-300": "#01050b",
          "base-content": "#fff",
          info: "#2094f3",
          success: "#51cf66",
          warning: "#ff922b",
          error: "#fa5252",
        },
      },
      "forest",
      "dracula",
      "halloween",
      "wireframe",
      "emerald",
      "valentine",
      "synthwave",
      "aqua",
      "retro",
      "luxury",
    ],
  },
};
